# Generated by Django 5.1.4 on 2025-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_alter_job_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('jobseeker', 'Job Seeker')], max_length=20),
        ),
    ]
