# Generated by Django 5.1.4 on 2025-06-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='applied_on',
            new_name='applied_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.CharField(default='test@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
