# Generated by Django 5.1.4 on 2025-06-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_rename_applied_on_application_applied_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_on',
        ),
    ]
