# Generated by Django 5.1.4 on 2025-06-18 15:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_application_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
