# Generated by Django 5.1.4 on 2025-06-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Software', 'Software Development'), ('Data', 'Data Science'), ('Cloud', 'Cloud Engineer'), ('Devops', 'DevOps Engineer'), ('Marketing', 'Marketing'), ('Design', 'Design'), ('Sales', 'Sales'), ('HR', 'Human Resources'), ('Finance', 'Finance')], default='Software', max_length=50),
        ),
    ]
